[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "immo-core"
version = "0.1.0"
dependencies = [
    "pandas>=2.0",
    "numpy",
    "numpy-financial",
    "openpyxl",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["scripts*"]